// Renders transactional/definitions.tsx into functions/_lib/generated/emails.js.
//   npm run build:emails
import { render } from '@react-email/components';
import fs from 'node:fs';
import path from 'node:path';
import { EMAILS } from '../transactional/definitions.js';

const out: Record<string, { subject: string; html: string; text: string }> = {};
for (const e of EMAILS) {
  const html = await render(e.element);
  const text = await render(e.element, { plainText: true });
  out[e.id] = { subject: e.subject, html, text };
}
const file = path.resolve(import.meta.dirname, '../../functions/_lib/generated/emails.js');
fs.writeFileSync(file, `// GENERATED by newsletter-sender/scripts/build-emails.tsx from transactional/*.tsx. Do not edit by hand.\nexport default ${JSON.stringify(out, null, 0)};\n`);
if (process.argv.includes('--preview')) {
  const dir = process.argv[process.argv.indexOf('--preview') + 1];
  fs.mkdirSync(dir, { recursive: true });
  for (const [id, t] of Object.entries(out)) fs.writeFileSync(path.join(dir, `${id}.html`), t.html);
}
console.log(`Built ${EMAILS.length} emails -> ${path.relative(process.cwd(), file)}`);
